app = "capstock-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "4000"
  PHX_SERVER = "true"
  DATABASE_PATH = "/app/db/stock_fetcher_prod.db"
  PHX_HOST = "capstock-backend.fly.dev"

[mounts]
  source = "stock_db_data"
  destination = "/app/db"

[[services]]
  protocol = "tcp"
  internal_port = 4000

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]